import { Occurrence, ActionPlan, Unit } from './types';

export const MOCK_OCCURRENCES: Occurrence[] = [
  {
    id: '1',
    number: 'OC-001',
    unit: Unit.NARANDIBA,
    creator: 'João Silva',
    supervisor: 'Ricardo Oliveira',
    farm: 'Fazenda Boa Vista',
    plot: 'T-04',
    category: 'Mecânica',
    subcategory: 'Colhedora',
    observation: 'Vazamento de óleo no sistema hidráulico.',
    isCompleted: false,
    createdAt: '2024-02-20T10:00:00Z',
    completedAt: '',
    sector: 'Mecânica',
    isDeleted: false,
  },
  {
    id: '2',
    number: 'OC-002',
    unit: Unit.PARAGUACU,
    creator: 'Maria Santos',
    supervisor: 'Ana Paula',
    farm: 'Fazenda Santa Helena',
    plot: 'T-12',
    category: 'Elétrica',
    subcategory: 'Iluminação',
    observation: 'Faróis auxiliares não funcionam.',
    isCompleted: true,
    createdAt: '2024-02-21T14:30:00Z',
    completedAt: '2024-02-22T10:00:00Z',
    sector: 'Elétrica',
    isDeleted: false,
  },
  {
    id: '3',
    number: 'OC-003',
    unit: Unit.NARANDIBA,
    creator: 'Pedro Costa',
    supervisor: 'Ricardo Oliveira',
    farm: 'Fazenda Rio Doce',
    plot: 'T-08',
    category: 'Operacional',
    subcategory: 'Manobra',
    observation: 'Dificuldade de acesso ao talhão devido a chuvas.',
    isCompleted: false,
    createdAt: '2024-02-22T08:15:00Z',
    completedAt: '',
    sector: 'Operacional',
    isDeleted: false,
  },
  {
    id: '4',
    number: 'OC-004',
    unit: Unit.PARAGUACU,
    creator: 'Carlos Lima',
    supervisor: 'Marcos Souza',
    farm: 'Fazenda Alvorada',
    plot: 'T-02',
    category: 'Segurança',
    subcategory: 'EPI',
    observation: 'Falta de luvas de proteção para a equipe.',
    isCompleted: false,
    createdAt: '2024-02-23T11:45:00Z',
    completedAt: '',
    sector: 'Segurança',
    isDeleted: false,
  },
];

export const MOCK_ACTION_PLANS: ActionPlan[] = [
  {
    id: 'ap1',
    occurrenceId: 'OC-001',
    unit: Unit.NARANDIBA,
    creator: 'João Silva',
    supervisor: 'Ricardo Oliveira',
    createdAt: '2024-02-20T11:00:00Z',
    startDate: '2024-02-21T08:00:00Z',
    endDate: '2024-03-01T17:00:00Z',
    description: 'Troca das mangueiras hidráulicas e vedação do reservatório.',
    isCompleted: false,
    farm: 'Fazenda Boa Vista',
    plot: 'T-04',
  },
  {
    id: 'ap2',
    occurrenceId: 'OC-003',
    unit: Unit.NARANDIBA,
    creator: 'Pedro Costa',
    supervisor: 'Ricardo Oliveira',
    createdAt: '2024-02-22T09:00:00Z',
    startDate: '2024-02-23T08:00:00Z',
    endDate: '2024-02-25T17:00:00Z', // Overdue based on current date 2024-03-04
    description: 'Nivelamento do solo na entrada do talhão.',
    isCompleted: false,
    farm: 'Fazenda Rio Doce',
    plot: 'T-08',
  },
  {
    id: 'ap3',
    occurrenceId: 'OC-004',
    unit: Unit.PARAGUACU,
    creator: 'Carlos Lima',
    supervisor: 'Marcos Souza',
    createdAt: '2024-02-23T12:00:00Z',
    startDate: '2024-02-24T08:00:00Z',
    endDate: '2024-03-10T17:00:00Z',
    description: 'Solicitação de compra de novos kits de EPI.',
    isCompleted: false,
    farm: 'Fazenda Alvorada',
    plot: 'T-02',
  },
];
